console.log(10 + "5");
var x = 10;
console.log((x += 5));
console.log(10 - null);
var x = 10;
console.log((x *= 2));
console.log(10 / "2");
console.log(10 % 3);
var x = 10;
console.log(10 ** 2);
var x = 10;
y = 5;
console.log(x > y && y < x);
console.log(10 === "10");
console.log(null ?? "default");
console.log(10 || "default");
console.log(!true);
var x = 10;
y = 5;
console.log(x & y);
console.log(x | y);
console.log(x ^ y);
var x = 10;
y = ++x;
console.log(x, y);
var x = 10;
y = x++;
console.log(x, y);
var x = 10;
console.log(++x);
console.log(x++);
var x = 10;
y = --x;
console.log(x, y);
var x = 10;
y = x--;
console.log(x, y);
var x = 10;
y = x > 5 ? "yes" : "no";
console.log(y);
var x = 10;
y = x > 5 ? "yes" : x > 3 ? "maybe" : "no";
console.log(y);
const obj = { a: { b: "c" } };
console.log(obj?.a?.b);
console.log(obj?.a?.c);
console.log(obj?.b?.c);
var x = null;
y = x ?? "default";
console.log(y);
var x = undefined;
y = x ?? "default";
console.log(y);
var x = 0;
y = x ?? "default";
console.log(y);
